version: "3"

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: on-failure:3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    image: yaroslavk1231/todo_web_app_backend:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/static
    networks:
      - app_network
  gateway:
    image: yaroslavk1231/todo_web_app_gateway:latest
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static:/static
    networks:
      - app_network
    depends_on:
      - backend
networks:
  app_network:
    driver: bridge
