version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
  backend:
    image: yaroslavk1231/todo_web_app_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
    networks:
      - app_network
  gateway:
    image: yaroslavk1231/todo_web_app_gateway
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static:/static
    networks:
      - app_network
    depends_on:
      - backend
networks:
  app_network:
    driver: bridge
